gos_web_socket:
    server:
        port: 1257        # The port the socket server will listen on
        host: 127.0.0.1   # The host ip to bind to
        router:
            resources:
                - '%kernel.project_dir%/config/g-downloader/routing.yaml'