<?php

namespace App\Tests\Functional\Manager;

use App\Converter\EntityConverter;
use App\Enum\ParserType;
use App\Manager\SettingsManager;
use App\Model\SettingsModel;
use App\Repository\SettingsRepository;
use App\Tests\Functional\Manager\Base\BasicManagerTestCase;

class SettingsManagerTest extends BasicManagerTestCase
{
    /** @var SettingsManager */
    protected $manager;

    /** @var SettingsRepository */
    protected $repository;

    /** @var int */
    protected $count = 0;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $entityConverter = new EntityConverter();
        $entityConverter->setEntityManager($this->containerInstance->get('doctrine.orm.entity_manager'));

        $this->manager = $this->loadManager(SettingsManager::class);
        $this->manager->setEntityConverter($entityConverter);

        $this->repository = $this->loadRepository(SettingsRepository::class);

        $this->count = $this->manager->getCount();
    }

    public function testGetSettings()
    {
        $fullSettings = $this->manager->getSettings();
        $redditSettings = $this->manager->getSettings(['type' => ParserType::Reddit]);

        $this->assertNotEmpty($fullSettings);
        $this->assertNotEmpty($redditSettings);

        $this->assertInstanceOf(SettingsModel::class, $fullSettings);
        $this->assertInstanceOf(SettingsModel::class, $redditSettings);
    }

    public function testGetParserSettings()
    {
        $redditSettings = $this->manager->getParserSettings(ParserType::Reddit);

        $this->assertNotEMpty($redditSettings);
        $this->assertInstanceOf(SettingsModel::class, $redditSettings);
    }
}