<?php

namespace App\Tests\Functional\Manager;

use App\Entity\User;
use App\Manager\UserManager;
use App\Tests\Functional\Manager\Base\BasicManagerTestCase;
use App\Utils\StringHelper;

class UserManagerTest extends BasicManagerTestCase
{
    /** @var UserManager */
    protected $manager;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->manager = $this->loadManager(UserManager::class);
    }

    public function testGetByUsernameOrEmail()
    {
        $existingUserUsername = 'stud3nt';
        $existingUserEmail = 'no-reply@test.g-downloader.com';

        $nonExistingUserUsername = StringHelper::randomStr(20);
        $nonExistingUserEmail = StringHelper::randomStr(16).'@not-exists.com';

        $this->assertEmpty($this->manager->getByUsernameOrEmail($nonExistingUserEmail));
        $this->assertEmpty($this->manager->getByUsernameOrEmail($nonExistingUserUsername));

        $userByUsername = $this->manager->getByUsernameOrEmail($existingUserUsername);
        $userByEmail = $this->manager->getByUsernameOrEmail($existingUserEmail);

        $this->assertNotEmpty($userByUsername);
        $this->assertNotEmpty($userByEmail);

        $this->assertInstanceOf(User::class, $userByUsername);
        $this->assertInstanceOf(User::class, $userByEmail);
    }
}